# Simple workflow for deploying static content to GitHub Pages
name: Check for plugin updates

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run Check For Updates
        run: |
          echo "--- Directory Listing ---"
          ls -la
          bun install
          bun run ./bin/updatePackages.ts

      - name: Commit and Push Changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add *
            git commit -m "Update packages"
            git push
          else
            echo "No changes to commit"
          fi
