# Simple workflow for deploying static content to GitHub Pages
name: Check for plugin updates

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      deployment_needed: ${{ steps.check-for-updates.outputs.deployment_needed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run Check For Updates
        id: check-for-updates
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          PAT: ${{ secrets.PAT }}
          ORG: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
        run: |
          echo "--- Directory Listing ---"
          ls -la
          bun install
          bun run ./bin/updatePackages.ts
        continue-on-error: true

      - name: Set deployment_needed
        id: set-deployment-needed
        run: |
          if [ "${{ steps.check-for-updates.outcome }}" == "success" ]; then
            echo "deployment_needed=false" >> $GITHUB_ENV
          elif [ "${{ steps.check-for-updates.outcome }}" == "failure" ] && [ "${{ steps.check-for-updates.outputs.exit_code }}" == "10" ]; then
            echo "deployment_needed=true" >> $GITHUB_ENV
          else
            echo "deployment_needed=false" >> $GITHUB_ENV
          fi

  deploy:
    needs: check-for-updates
    if: needs.check-for-updates.outputs.deployment_needed == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "source"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Make dist directory
        id: make-dist
        run: |
          mkdir -p dist

      - name: Run Bun To Generate Composer Files
        run: |
          echo "--- Directory Listing ---"
          ls -la
          cd source
          bun install
          bun run ./src/actions/generate-composer.ts --host ${{ github.repository_owner }} --out ../dist/packages.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # built files
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
