# Simple workflow for deploying static content to GitHub Pages
name: Check for plugin updates

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: "0 */8 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run Check For Updates
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          PAT: ${{ secrets.PAT }}
          ORG: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
        run: |
          echo "--- Directory Listing ---"
          ls -la
          bun install
          bun run ./bin/updatePackages.ts
