# This is a basic workflow to help you get started with Actions
name: New Package Version

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      slug:
        description: "Slug of the package to fetch"
        required: true
        type: string
      url:
        description: "URL of the package to fetch"
        required: true
        type: string
      version:
        description: "Version of the package being updated"
        required: true
        type: string
      vendor:
        description: "Vendor of the package being updated"
        required: false
        type: string
      type:
        description: "Whether the package is a theme or a plugin"
        required: true
        type: string

  workflow_call:
    inputs:
      slug:
        description: "Slug of the package to fetch"
        required: true
        type: string
      url:
        description: "URL of the package to fetch"
        required: true
        type: string
      version:
        description: "Version of the package being updated"
        required: true
        type: string
      vendor:
        description: "Vendor of the package being updated"
        required: false
        type: string
      type:
        description: "Whether the package is a theme or a plugin"
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate-should-update:
    runs-on: ubuntu-latest
    steps:
      # - name: debug inputs
      #   run: |
      #     echo "slug: ${{ inputs.slug }}"
      #     echo "version: ${{ inputs.version }}"
      #     echo "url: ${{ inputs.url }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run Bun To Confirm Package Version
        id: valid-update
        run: |
          bun install
          bun run ./src/check-package-version.ts --slug ${{ inputs.slug }} --update_version ${{ inputs.version }} --type ${{ inputs.type }} --vendor ${{ inputs.vendor }}

  handle-package-update:
    runs-on: ubuntu-latest
    needs: validate-should-update
    steps:
      - name: debug inputs
        run: |
          echo "Vendor: ${{ inputs.vendor }}"
          echo "slug: ${{ inputs.slug }}"
          echo "version: ${{ inputs.version }}"
          echo "url: ${{ inputs.url }}"
          echo "type: ${{ inputs.type }}"

      # Twofold: First we need to get the token into the future steps
      # and additionally we need to clone this repo into the baseRepo folder.
      - name: Add Token To Future Git Steps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }} # `ORG_ADMIN_TOKEN` is a secret that contains your PAT
          path: baseRepo

      # we need the token that is available inside the baseRepo folder so we need to CD into the baseRepo folder, even though we don't need to do anything with that repo at the moment. If we dont do this then we wont be able to tell if the private repo exists or not.
      - name: Check if remote package repo exists
        id: check-remote
        run: |
          cd baseRepo && 
          [ "$(git ls-remote https://github.com/${{ github.repository_owner }}/${{ inputs.slug }}.git 2> /dev/null)" ] && \
          { echo "EXISTS=true" >> "$GITHUB_OUTPUT"; } || \
          { echo "EXISTS=false" >> "$GITHUB_OUTPUT"; }

      # Make a repo if it doesn't exist, We want to also add the gitignore template simply so that its not an empty repo. Being an empty repo seems to make it difficult to clone down in the next step.
      - name: Create Repo if it doesn't exist
        if: ${{steps.check-remote.outputs.EXISTS == 'false'}}
        run: |
          echo "Creating repo"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/${{ github.repository_owner }}/repos \
          -d '{"name":"${{ inputs.slug }}","description":"This Repository Tracks the ${{inputs.slug}} private wordpress ${{inputs.type}}.","private":true,"has_issues":false,"has_projects":false,"has_wiki":false, "gitignore_template":"WordPress"}'

      - name: Clone ${{inputs.type}} Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }} # `ORG_ADMIN_TOKEN` is a secret that contains your PAT
          path: package
          repository: ${{ github.repository_owner }}/${{ inputs.slug }}

      - name: Initialize ${{inputs.type}} Repo
        if: ${{steps.check-remote.outputs.EXISTS == 'false'}}
        run: |
          cd package
          vendor=${{ inputs.vendor }}
          echo -e "{\n\"name\": \"${{inputs.vendor == '' && inputs.slug || inputs.vendor}}/${{inputs.slug}}\",\n\"description\": \"Private Repo tracking the paid ${{inputs.theme}} ${{inputs.slug}}\"\n\"type\": \"wordpress-${{inputs.type}}\"\n}" >> composer.json
          echo "---- Directory Structure ----"
          ls -la
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rm .gitignore
          echo "---- Directory Structure ----"
          ls -la
          echo " " >> .gitignore
          git status
          git add *
          git commit -m "Prepare ${{inputs.type}} Repo"
          git push

      # the way this works is that we will move the .git folder to a new folder, then delete everything in the package folder, then fetch the new package files, then move the .git folder back into the package folder. This is because we need to keep the git history of the package files.
      - name: Remove Git from Local Files
        run: |
          mkdir GitInfo
          cd package
          git init --separate-git-dir=../GitInfo/git
          cp .git ../GitInfo/gitBackup
          echo "---- New Git Folder ----"
          cat ../GitInfo/gitBackup

      - name: Remove Everything in ${{inputs.type}} Folder
        run: |
          echo "---- Directory Structure ----"
          ls -la
          rm -rf package
          echo "---- Directory Structure ----"
          ls -la
          mkdir package
          echo "---- Directory Structure ----"
          ls -la
          cd package
          echo "---- Directory Structure Package ----"
          ls -la

      - name: Fetch ${{inputs.type}} Files
        run: |
          curl -L "${{ inputs.url }}" > package.zip
          unzip package.zip -d package
          rm package.zip

      # Check the directory structure of the plugin to make sure that the slug provided was correct.

      - name: Check that the ${{inputs.type}} slug is correct
        run: |
          echo "---- Directory Structure of ${{inputs.type}} ----"
          cd package/${{ inputs.slug }} 
          ls -la

      # Now that we have the files locally lets make sure that the provided version & Slug matches the version in the plugin files

      - name: Check that the Version Matches provided Version
        run: |
          cd package/${{ inputs.slug }}
          if [[ "${{ inputs.type }}" == "plugin" ]]; then
            VERSION=$(grep -Poh "(^|\s|^\*)+(Version\s*:\s*)\K([0-9]|\.)*(?=\s|$)" *.php)
          elif [[ "${{ inputs.type }}" == "theme" ]]; then
            VERSION=$(grep -Poh "(^|\s|^\*)+(Version\s*:\s*)\K([0-9]|\.)*(?=\s|$)" style.css)
          else
            echo "Unknown type: ${{ inputs.type }}"
            exit 1
          fi
          echo "${{ inputs.type }} Version: $VERSION"
          echo "Input Version: ${{ inputs.version }}"
          echo "---"
          [[ $VERSION == "${{ inputs.version }}" ]] && \
          { echo "Versions Match"; } || \
          { echo "Version Match Failed" && exit 1; }

      - name: Add git back to the package folder
        run: |
          cd package/${{ inputs.slug }}
          mv ../../GitInfo/git .git

      - name: check git status
        run: |
          cd package/${{ inputs.slug }}
          git status

      # if a plugin author provides a composer json file use theirs, otherwise use the default we created when we initialized the repo.
      - name: Check if composer.json exists
        id: check-composer
        run: |
          cd package/${{ inputs.slug }}
          [ -f composer.json ] && echo "Composer File Exists" && echo "EXISTS=true">>$GITHUB_OUTPUT || echo "Composer File Does Not Exist" && echo "EXISTS=false">>$GITHUB_OUTPUT

      - name: Add Composer File if not exist
        if: ${{steps.check-composer.outputs.EXISTS == 'false'}}
        run: |
          cd package/${{ inputs.slug }}
          echo "--- Directory Structure ---"
          ls -la
          git checkout -- composer.json
          echo "--- Directory Structure ---"
          ls -la

      - name: Git Status 2
        run: |
          cd package/${{ inputs.slug }}
          git status

      # Finally push the new plugin files to the repo
      - name: Push ${{inputs.type}} Files
        run: |
          cd package/${{ inputs.slug }}
          git add -A
          git status
          git config --global credential.helper '!f() { sleep 1; echo "username=git token=${{ secrets.ORG_ADMIN_TOKEN }}"; }; f'
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update ${{inputs.type}} to ${{ inputs.version }}"
          git push
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Get Commit Hash
        id: get-commit-hash
        run: |
          cd package/${{ inputs.slug }}
          REFERENCE=$(git rev-parse --short HEAD)
          echo "Git Hash for ${{inputs.type}}: $REFERENCE"
          echo "REFERENCE=$REFERENCE" >> $GITHUB_OUTPUT

      # use node to the version of the plugin in the database.json file.
      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Pull Any Changes to the Database
        run: |
          cd baseRepo
          git pull

      - name: Update the ${{inputs.type}} version in the database
        id: valid-update
        run: |
          cd baseRepo
          bun install
          bun run ./src/update-package-version.ts --slug ${{ inputs.slug }} --update_version ${{ inputs.version }} --reference ${{ steps.get-commit-hash.outputs.REFERENCE }} --vendor ${{ inputs.vendor }} --type ${{ inputs.type }}

      - name: Push updated Database to the Repo
        run: |
          cd baseRepo
          git add data/database.json
          git status
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update ${{inputs.type}} ${{inputs.slug}} Version to ${{inputs.version}}"
          git push
