# This is a basic workflow to help you get started with Actions
name: New Plugin Version

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      vendor:
        description: "Name of the plugin to fetch"
        required: true
      slug:
        description: "Slug of the plugin to fetch"
        required: true
      url:
        description: "URL of the plugin to fetch"
        required: true
      version:
        description: "Version of the plugin being updated"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # validate-plugin-should-update:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup bun
  #       uses: oven-sh/setup-bun@v2

  #     - name: Run Bun To Confirm Plugin Version
  #       id: valid-update
  #       run: |
  #         bun install
  #         bun run ./src/check-plugin-version.ts --vendor $VENDOR --slug $SLUG --update_version $VERSION
  #       env:
  #         VENDOR: ${{ github.event.inputs.vendor }}
  #         SLUG: ${{ github.event.inputs.slug }}
  #         VERSION: ${{ github.event.inputs.version }}

  handle-plugin-update:
    runs-on: ubuntu-latest
    # needs: validate-plugin-should-update
    steps:
      - name: debug inputs
        run: |
          echo "vendor: $VENDOR"
          echo "slug: $SLUG"
          echo "version: $VERSION"
          echo "url: $URL"
        env:
          VENDOR: ${{ github.event.inputs.vendor }}
          SLUG: ${{ github.event.inputs.slug }}
          VERSION: ${{ github.event.inputs.version }}
          URL: ${{ github.event.inputs.url }}

      # Twofold: First we need to get the token into the future steps
      # and additionally we need to clone this repo into the baseRepo folder.
      - name: Add Token To Future Git Steps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }} # `ORG_ADMIN_TOKEN` is a secret that contains your PAT
          path: baseRepo

      # we need the token that is available inside the baseRepo folder so we need to CD into the baseRepo folder, even though we don't need to do anything with that repo at the moment. If we dont do this then we wont be able to tell if the private repo exists or not.
      - name: Check if remote plugin repo exists
        id: check-remote
        run: |
          cd baseRepo && 
          [ "$(git ls-remote https://github.com/$HOST/$SLUG.git 2> /dev/null)" ] && \
          { echo "EXISTS=true" >> "$GITHUB_OUTPUT"; } || \
          { echo "EXISTS=false" >> "$GITHUB_OUTPUT"; }
        env:
          HOST: ${{ github.repository_owner }}
          SLUG: ${{ github.event.inputs.slug }}

      # Make a repo if it doesn't exist, We want to also add the gitignore template simply so that its not an empty repo. Being an empty repo seems to make it difficult to clone down in the next step.
      - name: Create Repo if it doesn't exist
        if: ${{steps.check-remote.outputs.EXISTS == 'false'}}
        run: |
          echo "Creating repo"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ORG_ADMIN_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/${{ github.repository_owner }}/repos \
          -d '{"name":"${{ github.event.inputs.slug }}","description":"This Repository Tracks the ${{ github.event.inputs.vendor }} / ${{github.event.inputs.slug}} private wordpress plugin.","private":true,"has_issues":false,"has_projects":false,"has_wiki":false, "gitignore_template":"WordPress"}'

      - name: Clone Plugin Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }} # `ORG_ADMIN_TOKEN` is a secret that contains your PAT
          path: plugin
          repository: ${{ github.repository_owner }}/${{ github.event.inputs.slug }}

      - name: Initialize Plugin Repo
        if: ${{steps.check-remote.outputs.EXISTS == 'false'}}
        run: |
          cd plugin
          echo "{\n"name": "${{github.event.inputs.vendor}}/${{github.event.inputs.slug}}",\n"description": "Private Repo tracking the paid plugin.",\n"type": "wordpress-plugin"\n}" >> composer.json
          echo "---- Directory Structure ----"
          ls -la
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          rm .gitignore
          echo "---- Directory Structure ----"
          ls -la
          echo " " >> .gitignore
          git status
          git add *
          git commit -m "Prepare Plugin Repo"
          git push

      # the way this works is that we will move the .git folder to a new folder, then delete everything in the plugin folder, then fetch the new plugin files, then move the .git folder back into the plugin folder. This is because we need to keep the git history of the plugin files.
      - name: Remove Git from Local Files
        run: |
          mkdir GitInfo
          cd plugin
          git init --separate-git-dir=../GitInfo/git
          cp .git ../GitInfo/gitBackup
          echo "---- New Git Folder ----"
          cat ../GitInfo/gitBackup

      - name: Remove Everything in Plugin Folder
        run: |
          echo "---- Directory Structure ----"
          ls -la
          rm -rf plugin
          echo "---- Directory Structure ----"
          ls -la
          mkdir plugin
          echo "---- Directory Structure ----"
          ls -la
          cd plugin
          echo "---- Directory Structure plugin ----"
          ls -la

      - name: Fetch Plugin Files
        run: |
          curl -L "${{ github.event.inputs.url }}" > plugin.zip
          unzip plugin.zip -d plugin
          rm plugin.zip

      - name: Check Directory Structure
        run: |
          echo "---- Directory Structure of plugin ----"
          cd plugin/${{ github.event.inputs.slug }}
          ls -la
      # # Now that we have the files locally lets make sure that the provided version matches the version in the plugin files
      # - name: Check that the Version Matches provided
      #   run: |
      #     cd plugin/${{ github.event.inputs.slug }}
      #     grep -Po "(^|\s|^\*)+(Version\s*:\s*)\K([0-9]|\.)*(?=\s|$)" *

      - name: Add git back to the plugin folder
        run: |
          cd plugin/${{ github.event.inputs.slug }}
          mv ../../GitInfo/git .git

      - name: check git status
        run: |
          cd plugin/${{ github.event.inputs.slug }}
          git status

      # if a plugin author provides a composer json file use theirs, otherwise use the default we created when we initialized the repo.
      - name: Check if composer.json exists
        id: check-composer
        run: |
          cd plugin/${{ github.event.inputs.slug }}
          [ -f composer.json ] && echo "Composer File Exists" && echo "EXISTS=true">>$GITHUB_OUTPUT || echo "Composer File Does Not Exist" && echo "EXISTS=false">>$GITHUB_OUTPUT

      - name: Add Composer File if not exist
        if: ${{steps.check-composer.outputs.EXISTS == 'false'}}
        run: |
          cd plugin/${{ github.event.inputs.slug }}
          echo "--- Directory Structure ---"
          ls -la
          git checkout -- composer.json
          echo "--- Directory Structure ---"
          ls -la

      - name: Git Status 2
        run: |
          cd plugin/${{ github.event.inputs.slug }}
          git status

      # Finally push the new plugin files to the repo
      - name: Push Plugin Files
        run: |
          cd plugin/${{ github.event.inputs.slug }}
          git add -A
          git status
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update Plugin to ${{ github.event.inputs.version }}"
          git push

      # use node to the version of the plugin in the database.json file.
      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Run Bun To Confirm Plugin Version
        id: valid-update
        run: |
          cd baseRepo
          bun install
          bun run ./src/update-plugin-version.ts --vendor $VENDOR --slug $SLUG --update_version $VERSION
        env:
          VENDOR: ${{ github.event.inputs.vendor }}
          SLUG: ${{ github.event.inputs.slug }}
          VERSION: ${{ github.event.inputs.version }}
