name: Report Plugin Update List
on:
  workflow_dispatch:
    inputs:
      json:
        description: "List of updates in JSON format"
        required: true
jobs:
  update-plugin:
    strategy:
      max-parallel: 1
      matrix:
        value: ${{fromJSON(github.event.inputs.json)}}
      fail-fast: false
    uses: ./.github/workflows/new-update-version.yml
    with:
      slug: "${{ matrix.value.plugin_slug || matrix.value.theme_slug }}"
      url: "${{ matrix.value.plugin_update_url || matrix.value.theme_update_url }}"
      version: "${{ matrix.value.plugin_update_version || matrix.value.theme_update_version }}"
      vendor: "${{ matrix.value.plugin_vendor || matrix.value.theme_vendor }}"
      type: "${{ matrix.value.plugin_slug && 'plugin' || matrix.value.theme_slug && 'theme' }}"
    secrets: inherit
