name: "[DEBUG]" Plugin Update List"
on:
  workflow_dispatch:
    inputs:
      json:
        description: "List of updates in JSON format"
        required: true
jobs:
  update-package:
    strategy:
      max-parallel: 1
      matrix:
        value: ${{fromJSON(inputs.json)}}
      fail-fast: false
    uses: ./.github/workflows/new-update-debug.yml
    with:
      slug: "${{ matrix.value.slug }}"
      url: "${{ matrix.value.update_url }}"
      version: "${{ matrix.value.update_version  }}"
      vendor: "${{ matrix.value.vendor  }}"
      type: "${{ matrix.value.type }}"
    secrets: inherit
