name: Report Plugin Update List
on:
  workflow_dispatch:
    inputs:
      json:
        description: "List of plugins to update in JSON format"
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: debug inputs
        run: |
          echo "json: ${{ github.event.inputs.json }}"

      - id: matrix
        run: |
          echo "value=${{github.event.inputs.json}}" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
  build:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
