name: Report Plugin Update List
on:
  workflow_dispatch:
    inputs:
      json:
        description: "List of plugins to update in JSON format"
        required: true
# "json": "[\"a\", \"b\", \"c\"]"
jobs:
  runUpdate:
    # needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        value: ${{fromJSON(github.event.inputs.json)}}

    steps:
      - run: |
          echo "Name: ${{ matrix.value.plugin_name }}"
          echo "Version: ${{ matrix.value.plugin_version }}"
          echo "Update Version: ${{ matrix.value.plugin_update_version }}"
          echo "URL: ${{ matrix.value.plugin_update_url }}"
          echo "Slug: ${{ matrix.value.plugin_slug }}"
          echo "File: ${{ matrix.value.plugin_file }}"
